<?php

DEFINE ('DB_USER', $DATABASE['DB_USER']);
DEFINE ('DB_PASSWORD', $DATABASE['DB_PASSWORD']);
DEFINE ('DB_HOST', $DATABASE['DB_HOST']);
DEFINE ('DB_NAME', $DATABASE['DB_NAME']);

$dbc = @mysqli_connect(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);

?>